### ISSUE TITLE
docker pull problem

### ISSUE THREAD

**Issue by HanJin996** [sola-st/RepairAgent#1]
Dear author:
When I use "docker pull islemdockerdev/repair-agent:v1" to pull the docker image, there is a problem.
![image](https://github.com/sola-st/RepairAgent/assets/77650304/4a332576-6742-4995-8666-9367340f08df)
But if I pull the langchain's docker, there is all well.

**Comment by islem-esi** [comment]
Thank you for reporting the problem.

It should work now.
Please,let me know if it is the case.

If you get other issues, do not hesitate to report them.
